name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NAME=Santiago Lionel
      - LAST_NAME=Lorca
      - DOCUMENT=30904465
      - BIRTHDATE=1999-03-17
      - NUMBER=7574
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./bet_files/agency-1.csv:/bets.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
